# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-04 04:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('test', models.TextField()),
                ('collaboration', models.IntegerField(choices=[(0, 'private'), (1, 'shared'), (2, 'users')], default=0)),
                ('visibility', models.IntegerField(choices=[(0, 'private'), (1, 'shared'), (2, 'users'), (3, 'public')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('collaborators', models.ManyToManyField(to='home.Profile')),
            ],
        ),
        migrations.AlterField(
            model_name='playlist',
            name='collaborators',
            field=models.ManyToManyField(to='home.Profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='playlists',
            field=models.ManyToManyField(to='home.Playlist'),
        ),
        migrations.AddField(
            model_name='post',
            name='songs',
            field=models.ManyToManyField(to='home.Song'),
        ),
    ]
