# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-08 03:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='slug',
            field=models.CharField(default=datetime.datetime(2016, 12, 8, 3, 7, 26, 299968, tzinfo=utc), max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
