# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-08 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_playlist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='song',
            name='remixer',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
